// 注入脚本公共工具：与 helper 通信、DOM 构建、多语言文案。
export const BOOT = typeof window !== 'undefined' ? (window.__ZCODEPRO__ || {}) : {};
export const HELPER_URL = BOOT.helperUrl || 'http://127.0.0.1:47889';
const TOKEN = BOOT.token || '';

export function rpc(path, options = {}) {
  return fetch(HELPER_URL + path, {
    method: options.method || 'GET',
    headers: {
      'Content-Type': 'application/json',
      'X-ZCodePro-Token': TOKEN,
    },
    body: options.body ? JSON.stringify(options.body) : undefined,
  })
    .then((r) => r.json())
    .catch((err) => ({ ok: false, error: String(err && err.message || err) }));
}

// 配置缓存：菜单每次打开时拉取，保证设置弹窗里的开关即时生效
let configCache = { value: null, at: 0 };
export async function getConfig(force = false) {
  const now = Date.now();
  if (!force && configCache.value && now - configCache.at < 3000) return configCache.value;
  const res = await rpc('/config');
  if (res.ok && res.config) {
    configCache = { value: res.config, at: now };
    return res.config;
  }
  return configCache.value || { features: {} };
}
export function clearConfigCache() { configCache = { value: null, at: 0 }; }

const zh = {
  settingsTitle: 'ZCode Pro',
  tabFeatures: '功能',
  tabStyles: '样式',
  tabProxy: '代理',
  tabAgents: '全局提示词',
  agentsDesc: '写入 ~/.zcode/AGENTS.md，作为默认指令用于所有项目的每次会话；保存后从新会话起生效，项目内的 AGENTS.md 可补充或覆盖。内容超过 100KB 会被应用截断。',
  agentsPlaceholder: '填写希望所有项目默认遵循的指令；清空并保存即移除全局提示词',
  agentsSave: '保存',
  agentsSaved: '全局提示词已保存',
  agentsLoadFailed: '读取全局提示词失败',
  proxyDesc: '为 ZCode Pro 本地助手发起的网络访问设置 HTTP 代理：插件市场的更新与安装、Headroom 本体的检查更新与升级都会走该代理。不影响 ZCode 应用本身与模型请求，保存后立即生效。',
  proxyPlaceholder: 'http://127.0.0.1:7890',
  proxySave: '保存',
  proxySaved: '代理设置已保存',
  proxyHint: '留空保存即清除代理。',
  proxyTest: '检测',
  proxyTesting: '检测中…',
  proxyTestFailed: '检测失败',
  tabSync: '同步',
  syncDesc: '手动把 ZCode Pro 设置与模型设置备份到 WebDAV，或在新电脑上恢复。两项各自独立成文件，可只上传或只覆盖其中一项；仅在点击按钮时传输，不做自动同步。',
  syncUrlPlaceholder: 'https://dav.jianguoyun.com/dav/',
  syncDir: '上传目录',
  syncDirPlaceholder: 'zcode-pro',
  syncLogin: '登录',
  syncPassword: '密码',
  syncSave: '保存',
  syncSaved: '同步配置已保存',
  syncFormHint: '同步文件存到「上传目录」（默认 zcode-pro，可多级，自动创建）下的 zcodepro.json 与 model.json。',
  syncRecLink: '坚果云 WebDAV',
  syncRecSuffix: '：登录与密码填「应用密码」，不是账号密码。',
  syncIncludeZcp: 'ZCode Pro 设置',
  syncIncludeZcpDesc: '功能开关、样式调整、项目别名与代理设置；同步配置与凭据本身不参与同步。',
  syncIncludeModel: '模型设置',
  syncIncludeModelDesc: '自定义供应商与模型配置（config.json 与 provider_config.json，含 API Key）。账号登录的凭据（如 BigModel 订阅）不参与同步，各机器用各自账号登录。',
  syncUpload: '上传到云端',
  syncDownload: '从云端下载',
  syncUploading: '上传中…',
  syncDownloading: '下载中…',
  syncUploaded: '已上传到云端',
  syncDownloaded: '已从云端恢复',
  syncLastPush: '上次上传',
  syncLastPull: '上次下载',
  syncNever: '无',
  syncConfirmTitle: '从云端下载',
  syncConfirmDesc: '将用云端数据覆盖本机勾选的同步内容（覆盖前会在原文件旁留下 .zcodepro-backup 备份）；本机的同步配置与登录凭据不受影响。模型设置恢复后建议重启 ZCode 生效。确认下载？',
  syncConfirmGo: '确认下载',
  syncHint: '同步登录凭据仅保存在本机 zcodepro.json；模型设置包含自定义供应商的 API Key，只会上传到你自己的 WebDAV。',
  rowGapName: '段落间距',
  rowGapDesc: '会话中段落等文本块之间的垂直间距（回合之间、答案内部）。',
  listSpacingName: '列表上下边距',
  listSpacingDesc: '答案中列表上下的留白。',
  listItemSpacingName: '列表项间距',
  listItemSpacingDesc: '列表中相邻列表项之间的间距。',
  quoteCodeSpacingName: '引用块上下边距',
  quoteCodeSpacingDesc: '引用块与代码块上下的留白。',
  codeLineHeightName: '代码块行高',
  codeLineHeightDesc: '代码块内代码行的行高（倍数）。',
  tableSpacingName: '表格上下边距',
  tableSpacingDesc: '表格上下的留白。',
  tableCellPaddingName: '单元格上下/左右边距',
  tableCellPaddingDesc: '表格单元格内的留白；左输入框为上下、右为左右。',
  lineHeightName: '回答行高',
  lineHeightDesc: '回答正文的行高（倍数）。',
  userLineHeightName: '提问行高',
  userLineHeightDesc: '提问内容的行高（倍数）。',
  contentWidthName: '内容宽度',
  contentWidthDesc: '会话内容的最大宽度，可输入 px 或 %（如 900px、85%）；默认显示当前实际宽度，% 相对会话区域。',
  defaultValue: '默认',
  resetDefault: '恢复默认',
  featureProjectMenu: '项目菜单增强',
  featureProjectMenuDesc: '项目「更多」菜单中的自定义别名、切换文件夹、打开文件夹与复制路径（别名同时作用于侧边栏显示）。',
  featureTaskOrder: '侧边栏会话拖动排序',
  featureTaskOrderDesc: '让置顶、项目与分组中的会话拖动后记住顺序，刷新后保持。',
  featureSessionSwitch: '会话快捷切换',
  featureSessionSwitchDesc: 'alt+z 在当前与上次会话间来回切换；按住 alt 再按 x/c 弹出最近会话列表前后选择，松开 alt 切换（类 alt+tab）。',
  featureTitleLock: '重命名会话名锁定',
  featureTitleLockDesc: '手动重命名过的会话不再被自动标题覆盖：会话有新回答后界面可能改显自动标题，重启后又变回，本功能让侧栏始终显示重命名后的名字。',
  featureWsRunning: '折叠项目运行提示（实验性）',
  featureWsRunningDesc: '折叠的项目里仍有会话在运行时，项目图标旋转提示；全部结束或展开项目后恢复。期间每 60 秒在后台短暂展开该项目复核运行状态再收起，会话行不显示，仅项目位置可能有约四分之一秒的轻微高度起伏。',
  tabPerformance: '性能',
  perfDesc: 'ZCode 为每个打开过的项目常驻一个会话进程，应用自身不会回收，项目多了内存占用就高。开启后，长时间未使用且没有任务在跑的项目会被自动释放：会话记录不受影响，再次打开时自动恢复，仅首次回复有几秒等待。正在使用的项目、运行中的会话与后台命令、定时任务都不会被回收。后台命令检测依赖系统进程信息（Linux / macOS / Windows 各走系统自带工具），检测不可用时功能自动停用。',
  featureIdleReclaim: '空闲项目内存回收',
  featureIdleReclaimDesc: '满足条件的项目自动释放内存，会话不受影响，再次打开自动恢复。',
  idleReclaimMinutesLabel: '空闲多久后回收（分钟）',
  idleReclaimStartupLabel: '启动后多久回收一次（分钟）',
  idleReclaimStartupHint: '应用启动会为每个恢复的项目预热进程，到点把未使用的项目一次收掉；0 = 启动后立即回收，该次不受上一项空闲时长限制',
  idleReclaimUnit: '分钟',
  featureToolbarIcons: '侧栏菜单并入顶栏',
  featureToolbarIconsDesc: '把侧边栏顶部的「新建任务 / 搜索 / 自动化 / 插件市场」收成顶部导航栏（后退/前进旁）的图标按钮：悬停显示名称，对应界面打开时高亮，快捷键照常可用；侧边栏原菜单隐藏。',
  tbNewTask: '新建任务',
  tbSearch: '搜索',
  tbAutomations: '自动化',
  tbPluginStore: '插件市场',
  featurePinnedCollapse: '已置顶分区可折叠',
  featurePinnedCollapseDesc: '侧边栏「已置顶」标题可点击折叠/展开其任务列表（与「项目」「分组」分区一致），状态记住。',
  pinnedToggleAria: '折叠/展开已置顶',
  sidebarProjectSpacingName: '项目间距',
  sidebarProjectSpacingDesc: '侧边栏中相邻项目行之间的视觉间距（含行内留白）；设置后各分区（已置顶/项目/任务）之间的间距也统一为该值。',
  sidebarTaskSpacingName: '任务间距',
  sidebarTaskSpacingDesc: '侧边栏中相邻任务行之间的垂直间距（含行内上下留白）。',
  uiFontName: '界面字体',
  uiFontDesc: '除终端外所有界面文字的字体（终端字体在官方设置中调整）。',
  userFontName: '提问字体',
  userFontDesc: '会话中提问内容的字体；选「默认」时跟随界面字体。',
  assistantFontName: '回答字体',
  assistantFontDesc: '会话中回答正文的字体（代码块仍用等宽字体）；选「默认」时跟随界面字体。',
  switcherHint: 'x / c 选择，松开 alt 切换，Esc 取消',
  switcherCurrent: '当前',
  switcherEmpty: '暂无上次会话（切换过会话后可用）',
  switcherFailed: '未能切换到该会话（可能已删除）',
  featureFileActions: '文件菜单增强',
  featureFileActionsDesc: '在会话中文件链接的右键菜单里新增「默认应用打开」与「打开所在目录」。',
  featureImageCopy: '图片右键复制',
  featureImageCopyDesc: '右键会话中的图片或点击放大的预览图，可将图片复制到剪贴板。',
  imageCopy: '复制图片',
  imageCopied: '图片已复制到剪贴板',
  imageCopyFailed: '复制图片失败',
  openFolderItem: '打开文件夹',
  copyPathItem: '复制路径',
  pathCopied: '路径已复制到剪贴板',
  pathCopyFailed: '复制路径失败',
  fileOpenDefault: '默认应用打开',
  fileReveal: '打开所在目录',
  featurePinnedExpand: '置顶会话保持项目折叠（实验性）',
  featurePinnedExpandDesc: '点击折叠项目的置顶会话后将其保持折叠。受限于应用机制，项目会先短暂展开再缩起。',
  featureAutoUpdatePlugins: '自动更新 zcode-plugins 插件',
  featureAutoUpdatePluginsDesc: '启动时自动检查并更新已装的 zcode-plugins 插件（含安装市场里新增的插件），更新在新会话生效。',
  pluginsUpdateTitle: '插件更新 · zcode-plugins',
  pluginsCheckNow: '检查并更新',
  pluginsUpdating: '正在更新插件…',
  pluginsUpToDate: '插件已是最新',
  pluginsUpdatesFound: '{n} 个插件可更新',
  pluginsUpdatedDone: '已更新 {n} 个插件',
  pluginsUpdateFailed: '插件更新失败',
  pluginsUpdatesAvailable: 'zcode-plugins 有 {n} 个插件可更新（ZCode Pro 设置 → 功能）',
  pluginsAutoUpdated: 'zcode-plugins 插件已更新',
  tabVision: 'Vision',
  visionDesc: '主模型不支持图片输入时（如 glm-5.3），自动把消息里的图片交给下面的视觉模型识别，把描述带给主模型（zcode-vision 插件；/vision-* 命令编辑同一配置）。改动自动保存。',
  visionEnabled: '启用图片识别',
  visionForceIntercept: '主模型能看图也拦截',
  visionMode: '链模式',
  visionModeFallback: '依次尝试',
  visionModeFallbackDesc: '前一个失败才试下一个，任一成功即止（主力 + 备用）。',
  visionModePipeline: '逐级加工',
  visionModePipelineDesc: '每步都执行，后一步加工前一步结果（描述 → 校对/提炼）。',
  visionAddProxy: '添加代理',
  visionRemove: '删除',
  visionMoveUp: '上移',
  visionMoveDown: '下移',
  visionName: '名称',
  visionUseProvider: '供应商',
  visionUseProviderHint: '下拉选择或手动输入：session=跟随当前会话供应商，或供应商名/ID；设置后 baseUrl/API Key/格式自动取该供应商',
  visionUseProviderNone: '不跟随（自填地址）',
  visionUseProviderSession: '跟随当前会话（session）',
  visionUseProviderUnknown: '未找到该供应商，识别时会报错；请从下拉选择，或输入 session',
  visionSkipAfterFailures: '连续失败次数',
  visionSkipAfterFailuresHint: '某代理连续失败满次数后暂时跳过它，直接试下一个；0 = 不跳过',
  visionSkipMinutes: '跳过分钟数',
  visionSkipMinutesHint: '跳过多久后自动恢复尝试；期间任一次成功即清零计数',
  visionResetChain: '恢复默认链',
  visionResetChainConfirm: '将链模式与代理列表恢复为默认两级（glm-session → glm-flash），当前对代理的修改会丢失。继续？',
  visionBaseUrl: '接口地址 baseUrl',
  visionModel: '模型',
  visionFormat: '格式',
  visionApiKey: 'API Key',
  visionApiKeyHint: '留空自动取 GLM 订阅 key',
  visionPrompt: '识别提示词（pipeline 后续步可用 {prev} 引用上一步）',
  visionTest: '测试',
  visionTesting: '测试中…',
  visionTestFailed: '视觉代理测试失败',
  visionTestOutput: '测试输出',
  visionCompressKB: '压缩阈值 KB',
  visionCompressKBHint: '超过该大小的图先压缩再识别（最长边 2000、JPEG）；0 = 不压缩',
  visionLoadFailed: '读取视觉代理配置失败',
  tabRtk: 'rtk',
  rtkDesc: 'rtk 插件：把常见开发命令的输出压缩 60-90% 再进入上下文（/rtk-* 命令编辑同一配置）。改动自动保存并立即生效。',
  rtkEnabled: '启用 rtk 压缩',
  rtkNotInstalled: '未安装 rtk，以下配置将在安装后生效（会话里可用 /rtk-setup 安装）',
  rtkWhitelistTitle: '白名单（不压缩直接放行）',
  rtkBuiltinLabel: '内置放行（只读，随插件更新）：',
  rtkWhitelistDesc: '每条 name（如 docker）或 git:name（如 git:clone）。输出极小或纯副作用的命令无需压缩，加入后不再压缩；内置的 git add/commit/push、mkdir/cp 等不可移除。删除本文件即恢复默认。',
  rtkWhitelistPlaceholder: 'name 或 git:name，回车添加',
  rtkWhitelistAdd: '添加',
  rtkWhitelistClear: '清空',
  rtkWhitelistCleared: '白名单已清空',
  rtkWhitelistInvalid: '条目格式应为 name 或 git:name',
  rtkLoadFailed: '读取 rtk 配置失败',
  tabHeadroom: 'Headroom',
  headroomDesc: 'Headroom 插件：本地压缩代理驻留 127.0.0.1（默认 8787 端口），压缩发往模型的上下文以省 token（/hr-* 命令编辑同一配置）。压缩设备与省电切换保存后立即生效；切换设备会重启代理，正在处理的请求可能中断一次。',
  headroomBinMissing: '未找到 headroom 程序，代理无法启动；安装 headroom 后以下设置自动生效',
  headroomInstallTitle: '未安装 headroom 插件',
  headroomInstallDesc: '从 zcode-plugins 市场安装后即可在此管理压缩代理；建议安装后重启会话生效。',
  headroomInstall: '安装',
  headroomInstalling: '安装中…',
  headroomInstalled: '已安装 headroom 插件',
  headroomInstallRetry: '安装未生效，请重试或手动在插件市场安装',
  headroomLoadFailed: '读取 Headroom 配置失败',
  headroomStatusTitle: '运行状态',
  headroomStatusLoadFailed: '读取运行状态失败',
  headroomProxyUp: '代理运行中',
  headroomProxyDown: '代理未运行',
  headroomCurrentBackend: '当前设备',
  headroomDesiredBackend: '目标设备',
  hrValAuto: '自动',
  hrPmAc: '交流电',
  hrPmBattery: '电池',
  hrPmSaver: '省电模式',
  hrPmSaverBat: '省电模式+电池',
  hrDetectOk: '正常',
  hrDetectMissing: '未安装',
  hrDetectBroken: '不可用',
  headroomPowerState: '电源',
  headroomWatcher: '监视器',
  headroomWatcherOn: '运行中',
  headroomWatcherOff: '已停止',
  headroomSaverDetect: '省电模式检测',
  headroomRefresh: '刷新',
  headroomStart: '启动',
  headroomRestart: '重启',
  headroomStopAction: '停止',
  headroomStopTitle: '停止 Headroom 代理',
  headroomStopDesc: '停止后，ZCode 中指向该代理（127.0.0.1）的供应商将无法连接，直至重新启动代理。确认停止？',
  headroomStoppedWarn: '代理已停止；指向 127.0.0.1 的供应商将无法连接',
  headroomBackend: '压缩设备',
  headroomBackendAuto: '自动 · 显卡优先',
  headroomBackendCpu: 'CPU · 省电',
  headroomBackendNative: '（原生值）',
  headroomBackendDesc: '自动：headroom 选最快设备（CUDA/MPS 显卡优先）；CPU：强制 CPU 压缩，省电且不占显存。也支持 headroom 原生值（onnx、pytorch_mps 等）。切换会重启代理立即生效。',
  headroomPower: '省电自动切换',
  headroomPowerOff: '关闭',
  headroomPowerOffDesc: '不自动切换，始终按「压缩设备」运行。',
  headroomPowerBattery: '用电池时',
  headroomPowerBatteryDesc: '拔电（电池放电）→ CPU 压缩，插电自动切回。',
  headroomPowerSaver: '省电模式时',
  headroomPowerSaverDesc: '仅系统进入省电模式 → CPU 压缩，退出切回。',
  hrCpuPinnedHint: '压缩设备已固定为 CPU，省电自动切换不会再改变它。',
  headroomInterval: '监视间隔',
  headroomIntervalDesc: '省电监视器轮询电源状态的间隔（10–3600 秒，默认 60）；保存后从下一轮巡检起生效，无需重启。',
  headroomSecUnit: '秒',
  headroomVersionPlugin: '插件',
  headroomVersionBin: '程序',
  upgradeCheck: '检查更新',
  upgradeChecking: '检查中…',
  upgradeUpToDate: '已是最新（{v}）',
  upgradeFound: '可升级到 {v}',
  upgradeNow: '升级',
  upgradeRunning: '升级中…',
  upgradeStop: '停止升级',
  upgradeStopped: '已停止升级',
  upgradeDone: '已更新到 {v}',
  upgradeFinished: '升级完成',
  upgradeCheckFailed: '检查更新失败',
  version: '版本',
  close: '关闭',
  cancel: '取消',
  pathLabel: '路径',
  aliasItem: '自定义别名',
  aliasTitle: '自定义项目别名',
  aliasDesc: '仅在 ZCode 界面中显示该别名，不修改磁盘目录与任何数据，随时可清除恢复。',
  aliasLabel: '别名',
  aliasPlaceholder: '留空并保存 = 恢复真实名称',
  aliasConfirm: '保存',
  aliasClear: '恢复真实名称',
  aliasSaved: '别名已更新',
  aliasCleared: '已恢复真实名称',
  aliasHint: '磁盘目录名不变：终端、文件管理器与其他引用真实路径的界面仍显示原名。',
  taskOrderSaved: '顺序已更新',
  qqGroupTitle: 'QQ 群：428403354',
  qqGroupDesc: '问题反馈与交流',
  wechatGroupTitle: '微信群',
  wechatGroupDesc: '添加微信 {id} 邀请进群',
  wechatIdCopied: '微信号已复制',
  browse: '浏览',
  relocateItem: '切换文件夹',
  relocateTitle: '切换文件夹',
  relocateDesc: '将该项目指向另一个文件夹：侧边栏、已打开标签页与本地任务历史一并迁移，目录本身不会被移动，会话记录不会丢失。',
  relocateNewPathLabel: '新文件夹',
  relocateConfirm: '移动',
  relocateHint: '目标文件夹需已存在，可输入路径或点击「浏览」选择；完成后界面将自动刷新。',
  relocateSuccess: '已切换文件夹，正在刷新界面…',
  relocateIndexSkipped: '已切换文件夹；任务历史未能同步（本机缺少 SQLite 支持），旧任务条目可能仍指向旧路径。',
  relocateSame: '新文件夹与当前文件夹相同',
  relocateNotFound: '目标文件夹不存在',
  relocateProtected: '拒绝指向 ZCode 数据目录内部路径',
  relocateIndexBusy: '任务索引正被 ZCode 占用，请稍后重试。',
  relocateConfirmTitle: '确认切换文件夹',
  relocateConfirmDesc: '切换后将自动刷新页面，聊天输入框中未发送的内容会丢失；会话记录与项目文件不受影响。',
  relocateConfirmGo: '确认切换',
  failed: '操作失败',
  retryHint: '请重试',
};

const en = {
  settingsTitle: 'ZCode Pro',
  tabFeatures: 'Features',
  tabStyles: 'Styles',
  tabProxy: 'Proxy',
  tabAgents: 'Global Prompt',
  agentsDesc: 'Written to ~/.zcode/AGENTS.md and used as default instructions in every session across all projects. Takes effect for new sessions; per-project AGENTS.md can extend or override it. Content over 100 KB is truncated by the app.',
  agentsPlaceholder: 'Instructions followed by all projects by default; save empty to remove the global prompt',
  agentsSave: 'Save',
  agentsSaved: 'Global prompt saved.',
  agentsLoadFailed: 'Failed to load the global prompt',
  proxyDesc: 'Set an HTTP proxy for network access made by the local helper: plugin marketplace updates and installs, headroom update checks and upgrades. Does not affect the ZCode app itself or model requests. Applies immediately.',
  proxyPlaceholder: 'http://127.0.0.1:7890',
  proxySave: 'Save',
  proxySaved: 'Proxy settings saved.',
  proxyHint: 'Save empty to clear the proxy.',
  proxyTest: 'Test',
  proxyTesting: 'Testing…',
  proxyTestFailed: 'Test failed',
  tabSync: 'Sync',
  syncDesc: 'Manually back up ZCode Pro settings and model settings to WebDAV, or restore them on a new computer. The two items are stored as separate files, so you can upload or overwrite either one alone; data moves only when you click, never automatically.',
  syncUrlPlaceholder: 'https://dav.example.com/dav/',
  syncDir: '上传目录',
  syncDirPlaceholder: 'zcode-pro',
  syncLogin: 'Login',
  syncPassword: 'Password',
  syncSave: 'Save',
  syncSaved: 'Sync settings saved.',
  syncFormHint: 'Sync files go to zcodepro.json and model.json inside the folder (default zcode-pro, multi-level allowed, created automatically).',
  syncRecLink: 'Jianguoyun WebDAV',
  syncRecSuffix: ' — use the app password, not your account password.',
  syncIncludeZcp: 'ZCode Pro settings',
  syncIncludeZcpDesc: 'Feature toggles, style adjustments, project aliases and the proxy setting; the sync config and credentials themselves are never synced.',
  syncIncludeModel: 'Model settings',
  syncIncludeModelDesc: 'Custom providers and model config (config.json and provider_config.json, API keys included). Account sign-in credentials (e.g. the BigModel subscription) are not synced; each computer signs in with its own account.',
  syncUpload: 'Upload',
  syncDownload: 'Download',
  syncUploading: 'Uploading…',
  syncDownloading: 'Downloading…',
  syncUploaded: 'Uploaded to the server.',
  syncDownloaded: 'Restored from the server.',
  syncLastPush: 'Last upload',
  syncLastPull: 'Last download',
  syncNever: 'never',
  syncConfirmTitle: 'Download from the server',
  syncConfirmDesc: 'Cloud data will overwrite the selected sections locally (a .zcodepro-backup copy is kept next to each file); your local sync config and credentials stay untouched. Restarting ZCode is recommended after restoring model settings. Download now?',
  syncConfirmGo: 'Download',
  syncHint: 'Sync credentials are stored locally in zcodepro.json only; model settings contain the API keys of custom providers and go to your own WebDAV only.',
  rowGapName: 'Paragraph spacing',
  rowGapDesc: 'Vertical spacing between text blocks (turns, paragraphs inside answers).',
  listSpacingName: 'List spacing',
  listSpacingDesc: 'Space above and below lists.',
  listItemSpacingName: 'List item spacing',
  listItemSpacingDesc: 'Spacing between adjacent list items.',
  quoteCodeSpacingName: 'Quote block spacing',
  quoteCodeSpacingDesc: 'Space above and below quotes and code blocks.',
  codeLineHeightName: 'Code line height',
  codeLineHeightDesc: 'Line height of lines inside code blocks (multiplier).',
  tableSpacingName: 'Table spacing',
  tableSpacingDesc: 'Space above and below tables.',
  tableCellPaddingName: 'Cell padding (V/H)',
  tableCellPaddingDesc: 'Padding inside table cells; left input is vertical, right is horizontal.',
  lineHeightName: 'Answer line height',
  lineHeightDesc: 'Line height of answer text (multiplier).',
  userLineHeightName: 'Question line height',
  userLineHeightDesc: 'Line height of question text (multiplier).',
  contentWidthName: 'Content width',
  contentWidthDesc: 'Max width of conversation content; accepts px or % (e.g. 900px, 85%).',
  defaultValue: 'default',
  resetDefault: 'Reset to default',
  featureProjectMenu: 'Project menu actions',
  featureProjectMenuDesc: 'Custom alias, switch folder, open folder and copy path in the project "More" menu (the alias also applies to the sidebar).',
  featureTaskOrder: 'Sidebar session drag ordering',
  featureTaskOrderDesc: 'Makes session drags in Pinned, Projects and Groups persist across refreshes.',
  featureSessionSwitch: 'Session quick switch',
  featureSessionSwitchDesc: 'alt+z toggles between the current and the last session; hold alt and press x/c to move the highlight across recently used sessions, release alt to switch (like alt+tab).',
  featureTitleLock: 'Keep renamed session titles',
  featureTitleLockDesc: 'Sessions you renamed keep their custom title: after new replies the app may show an auto-generated title instead, which reverts after a restart; this keeps the renamed title in the sidebar.',
  featureWsRunning: 'Running indicator on collapsed projects (experimental)',
  featureWsRunningDesc: 'Spins a collapsed project\'s icon while any of its sessions is still running; stops when they all finish or the project is expanded. While spinning, the project is briefly re-expanded in the background every 60 s to re-check and then collapsed — rows stay hidden, with only a subtle quarter-second height ripple at the project.',
  tabPerformance: 'Performance',
  perfDesc: 'ZCode keeps a session process resident for every project you have opened and never reclaims it, so memory grows with projects. When enabled, projects unused for a while with nothing running release their memory automatically: sessions are untouched and reload when reopened, with a few seconds wait on the first reply. The project in use, running sessions, background commands and scheduled tasks are never reclaimed. Background-command detection reads system process info via built-in tools (Linux / macOS / Windows); when unavailable, the feature disables itself.',
  featureIdleReclaim: 'Idle project memory reclaim',
  featureIdleReclaimDesc: 'Qualifying projects release their memory; sessions are untouched and reload when reopened.',
  idleReclaimMinutesLabel: 'Idle minutes before reclaim',
  idleReclaimStartupLabel: 'Minutes after startup for a one-shot reclaim',
  idleReclaimStartupHint: 'Startup pre-spawns a process per restored project; this pass collects the unused ones once. 0 = reclaim right after startup, ignoring the idle minutes above',
  idleReclaimUnit: 'min',
  featureToolbarIcons: 'Sidebar menu in the top bar',
  featureToolbarIconsDesc: 'Turns the sidebar menu (New task / Search / Automations / Plugin store) into icon buttons next to the back/forward arrows in the top bar: hover shows the name, the button stays highlighted while its view is open, and shortcuts still work; the original sidebar menu is hidden.',
  tbNewTask: 'New task',
  tbSearch: 'Search',
  tbAutomations: 'Automations',
  tbPluginStore: 'Plugin store',
  featurePinnedCollapse: 'Collapsible Pinned section',
  featurePinnedCollapseDesc: 'The sidebar "Pinned" header collapses/expands its task list (like Projects and Groups); the state is remembered.',
  pinnedToggleAria: 'Collapse/expand Pinned',
  sidebarProjectSpacingName: 'Project spacing',
  sidebarProjectSpacingDesc: 'Visual spacing between adjacent project rows in the sidebar (row padding included); when set, section gaps (Pinned/Projects/Tasks) follow the same value.',
  sidebarTaskSpacingName: 'Task spacing',
  sidebarTaskSpacingDesc: 'Vertical spacing between adjacent task rows in the sidebar (row padding included).',
  uiFontName: 'UI font',
  uiFontDesc: 'Font for all interface text except the terminal (its font is set in the official settings).',
  userFontName: 'Question font',
  userFontDesc: 'Font of question text in conversations; "default" follows the UI font.',
  assistantFontName: 'Answer font',
  assistantFontDesc: 'Font of answer text in conversations (code blocks stay monospaced); "default" follows the UI font.',
  switcherHint: 'x / c to choose, release alt to switch, Esc to cancel',
  switcherCurrent: 'current',
  switcherEmpty: 'No previous session yet (available after you switch sessions)',
  switcherFailed: 'Failed to switch to that session (it may have been deleted)',
  featureFileActions: 'File menu actions',
  featureFileActionsDesc: 'Adds "Open with default app" and "Reveal in file manager" to the right-click menu of file links in chat.',
  featureImageCopy: 'Image right-click copy',
  featureImageCopyDesc: 'Right-click an image in chat or the enlarged preview to copy it to the clipboard.',
  imageCopy: 'Copy image',
  imageCopied: 'Image copied to the clipboard.',
  imageCopyFailed: 'Failed to copy the image.',
  openFolderItem: 'Open folder',
  copyPathItem: 'Copy path',
  pathCopied: 'Path copied to the clipboard.',
  pathCopyFailed: 'Failed to copy the path.',
  fileOpenDefault: 'Open with default app',
  fileReveal: 'Reveal in file manager',
  featurePinnedExpand: 'Keep projects collapsed for pinned sessions (experimental)',
  featurePinnedExpandDesc: 'Keeps the project collapsed after clicking a pinned session. Note: it briefly expands first, then collapses.',
  featureAutoUpdatePlugins: 'Auto-update zcode-plugins plugins',
  featureAutoUpdatePluginsDesc: 'Checks and updates installed zcode-plugins plugins on startup (including newly added ones). Updates apply to new sessions.',
  pluginsUpdateTitle: 'Plugin updates · zcode-plugins',
  pluginsCheckNow: 'Check & update',
  pluginsUpdating: 'Updating plugins…',
  pluginsUpToDate: 'Plugins are up to date',
  pluginsUpdatesFound: '{n} plugin(s) can be updated',
  pluginsUpdatedDone: 'Updated {n} plugin(s)',
  pluginsUpdateFailed: 'Plugin update failed',
  pluginsUpdatesAvailable: '{n} zcode-plugins update(s) available (ZCode Pro settings → Features)',
  pluginsAutoUpdated: 'zcode-plugins updated',
  tabVision: 'Vision',
  visionDesc: 'When the main model cannot see images (e.g. glm-5.3), images in messages are recognized by the vision models below and passed to the main model as text (zcode-vision plugin; /vision-* commands edit the same file). Changes save automatically.',
  visionEnabled: 'Enable image recognition',
  visionForceIntercept: 'Intercept even if the main model sees images',
  visionMode: 'Chain mode',
  visionModeFallback: 'Fallback',
  visionModeFallbackDesc: 'Try in order until one succeeds (primary + backup).',
  visionModePipeline: 'Pipeline',
  visionModePipelineDesc: 'Every step runs; later steps refine earlier results (describe → refine).',
  visionAddProxy: 'Add proxy',
  visionRemove: 'Remove',
  visionMoveUp: 'Up',
  visionMoveDown: 'Down',
  visionName: 'Name',
  visionUseProvider: 'Provider',
  visionUseProviderHint: 'Pick from the list or type: session = follow the current session provider, or a provider name/ID; baseUrl/API key/format follow that provider',
  visionUseProviderNone: 'Not following (enter base URL)',
  visionUseProviderSession: 'Follow session provider (session)',
  visionUseProviderUnknown: 'Unknown provider; recognition will fail. Pick from the list or type session',
  visionSkipAfterFailures: 'Skip after failures',
  visionSkipAfterFailuresHint: 'After this many consecutive failures a proxy is skipped and the next one is tried; 0 = never skip',
  visionSkipMinutes: 'Skip minutes',
  visionSkipMinutesHint: 'How long a skipped proxy rests before being retried; any success resets the counter',
  visionResetChain: 'Reset default chain',
  visionResetChainConfirm: 'Reset chain mode and the proxy list to the default 2-level chain (glm-session → glm-flash)? Current proxy edits will be lost. Continue?',
  visionBaseUrl: 'Base URL',
  visionModel: 'Model',
  visionFormat: 'Format',
  visionApiKey: 'API Key',
  visionApiKeyHint: 'Leave empty to reuse the GLM subscription key',
  visionPrompt: 'Recognition prompt ({prev} = previous step in pipeline)',
  visionTest: 'Test',
  visionTesting: 'Testing…',
  visionTestFailed: 'Vision proxy test failed',
  visionTestOutput: 'Test output',
  visionCompressKB: 'Compress threshold KB',
  visionCompressKBHint: 'Images above this size are compressed first (max edge 2000, JPEG); 0 = never',
  visionLoadFailed: 'Failed to load the vision config',
  tabRtk: 'rtk',
  rtkDesc: 'rtk plugin: compresses common dev command output by 60-90% before it reaches the context (/rtk-* commands edit the same files). Changes save automatically and apply immediately.',
  rtkEnabled: 'Enable rtk compression',
  rtkNotInstalled: 'rtk is not installed. The settings below take effect after installation (/rtk-setup in a session).',
  rtkWhitelistTitle: 'Whitelist (pass through without compression)',
  rtkBuiltinLabel: 'Built-in exemptions (read-only, follow plugin updates):',
  rtkWhitelistDesc: 'Each entry is name (e.g. docker) or git:name (e.g. git:clone). Commands with tiny or no output need no compression; adding them skips compression. Built-ins (git add/commit/push, mkdir/cp, …) cannot be removed. Delete the file to reset.',
  rtkWhitelistPlaceholder: 'name or git:name, press Enter to add',
  rtkWhitelistAdd: 'Add',
  rtkWhitelistClear: 'Clear',
  rtkWhitelistCleared: 'Whitelist cleared',
  rtkWhitelistInvalid: 'Entry must be name or git:name',
  rtkLoadFailed: 'Failed to load the rtk config',
  tabHeadroom: 'Headroom',
  headroomDesc: 'Headroom plugin: a local compression proxy on 127.0.0.1 (port 8787 by default) that compresses context sent to the model to save tokens (/hr-* commands edit the same file). Device and power-save changes apply immediately; switching the device restarts the proxy, so requests in progress may be interrupted once.',
  headroomBinMissing: 'The headroom program was not found, so the proxy cannot start. The settings below take effect once it is installed.',
  headroomInstallTitle: 'headroom plugin not installed',
  headroomInstallDesc: 'Install it from the zcode-plugins marketplace to manage the compression proxy here; restarting the session afterwards is recommended.',
  headroomInstall: 'Install',
  headroomInstalling: 'Installing…',
  headroomInstalled: 'headroom plugin installed',
  headroomInstallRetry: 'Installation did not take effect; retry or install it from the marketplace manually',
  headroomLoadFailed: 'Failed to load the Headroom config',
  headroomStatusTitle: 'Status',
  headroomStatusLoadFailed: 'Failed to load the status',
  headroomProxyUp: 'Proxy running',
  headroomProxyDown: 'Proxy down',
  headroomCurrentBackend: 'Current device',
  headroomDesiredBackend: 'Target device',
  hrValAuto: 'Auto',
  hrPmAc: 'AC',
  hrPmBattery: 'Battery',
  hrPmSaver: 'Power saver',
  hrPmSaverBat: 'Saver + battery',
  hrDetectOk: 'OK',
  hrDetectMissing: 'missing',
  hrDetectBroken: 'unavailable',
  headroomPowerState: 'Power',
  headroomWatcher: 'Watcher',
  headroomWatcherOn: 'Running',
  headroomWatcherOff: 'Stopped',
  headroomSaverDetect: 'Power-saver detection',
  headroomRefresh: 'Refresh',
  headroomStart: 'Start',
  headroomRestart: 'Restart',
  headroomStopAction: 'Stop',
  headroomStopTitle: 'Stop the Headroom proxy',
  headroomStopDesc: 'Providers in ZCode that point at this proxy (127.0.0.1) will fail to connect until it is started again. Stop it?',
  headroomStoppedWarn: 'Proxy stopped; providers pointing at 127.0.0.1 cannot connect.',
  headroomBackend: 'Compression device',
  headroomBackendAuto: 'Auto · GPU first',
  headroomBackendCpu: 'CPU · power saving',
  headroomBackendNative: ' (native)',
  headroomBackendDesc: 'Auto lets headroom pick the fastest device (CUDA/MPS); CPU forces CPU compression (power saving, no VRAM). Native headroom values (onnx, pytorch_mps, …) also work. Switching restarts the proxy to apply.',
  headroomPower: 'Power-save auto switch',
  headroomPowerOff: 'Off',
  headroomPowerOffDesc: 'No auto switching; always follow the compression device.',
  headroomPowerBattery: 'On battery',
  headroomPowerBatteryDesc: 'On battery (discharging) → CPU; switches back when plugged in.',
  headroomPowerSaver: 'Power-saver',
  headroomPowerSaverDesc: 'Only the system power-saver mode → CPU; back when it exits.',
  hrCpuPinnedHint: 'The compression device is pinned to CPU, so power-save switching no longer changes anything.',
  headroomInterval: 'Watch interval',
  headroomIntervalDesc: 'Seconds between power checks (10–3600, default 60); applies from the next round, no restart needed.',
  headroomSecUnit: 's',
  headroomVersionPlugin: 'plugin',
  headroomVersionBin: 'program',
  upgradeCheck: 'Check update',
  upgradeChecking: 'Checking…',
  upgradeUpToDate: 'Up to date ({v})',
  upgradeFound: '{v} available',
  upgradeNow: 'Update',
  upgradeRunning: 'Updating…',
  upgradeStop: 'Stop',
  upgradeStopped: 'Upgrade stopped',
  upgradeDone: 'Updated to {v}',
  upgradeFinished: 'Update finished',
  upgradeCheckFailed: 'Update check failed',
  version: 'Version',
  close: 'Close',
  cancel: 'Cancel',
  pathLabel: 'Path',
  aliasItem: 'Custom alias',
  aliasTitle: 'Custom alias',
  aliasDesc: 'Shown in the ZCode UI only. The directory on disk and all data stay untouched; revert anytime.',
  aliasLabel: 'Alias',
  aliasPlaceholder: 'Leave empty and save to restore the real name',
  aliasConfirm: 'Save',
  aliasClear: 'Restore real name',
  aliasSaved: 'Alias updated.',
  aliasCleared: 'Real name restored.',
  aliasHint: 'The directory name on disk is unchanged: terminals, file managers and other path-based UI still show the real name.',
  taskOrderSaved: 'Order updated.',
  qqGroupTitle: 'QQ group: 428403354',
  qqGroupDesc: 'Feedback & discussion',
  wechatGroupTitle: 'WeChat group',
  wechatGroupDesc: 'Add WeChat {id} for a group invite',
  wechatIdCopied: 'WeChat ID copied.',
  browse: 'Browse',
  relocateItem: 'Switch folder',
  relocateTitle: 'Switch folder',
  relocateDesc: 'Points this project at another folder: the sidebar, open tabs and local task history move along. The directory itself is not moved and no sessions are lost.',
  relocateNewPathLabel: 'New folder',
  relocateConfirm: 'Move',
  relocateHint: 'The target folder must already exist. Enter a path or use Browse; the UI refreshes automatically afterwards.',
  relocateSuccess: 'Folder switched. Refreshing…',
  relocateIndexSkipped: 'Folder switched, but the task history was not synced (SQLite support missing); old entries may still point to the old path.',
  relocateSame: 'The new folder is the same as the current one.',
  relocateNotFound: 'The target folder does not exist.',
  relocateProtected: 'Refusing to point inside the ZCode data directory.',
  relocateIndexBusy: 'The task index is busy (ZCode may be writing). Please retry shortly.',
  relocateConfirmTitle: 'Confirm folder switch',
  relocateConfirmDesc: 'The page will refresh after switching, and unsent text in the chat input will be lost. Sessions and project files are not affected.',
  relocateConfirmGo: 'Confirm switch',
  failed: 'Operation failed',
  retryHint: 'Please retry',
};

// 界面语言：与官方 IntlProvider 的解析一致——先读应用的 localStorage 偏好
// （zcode-locale-preference：zh-CN/en-US/system），'system' 或读取失败时回退 navigator.language
export function isZhLocale() {
  let pref = null;
  try { pref = window.localStorage.getItem('zcode-locale-preference'); } catch { /* ignore */ }
  if (pref === 'zh-CN' || pref === 'en-US') return pref === 'zh-CN';
  return /^zh/i.test(navigator.language || 'zh-CN');
}

export function t() {
  return isZhLocale() ? zh : en;
}

// helper 错误消息的英文映射（code → 文案）：helper 原文为中文，非中文界面按 code 显示英文，
// 无映射或中文界面回退 helper 原文
const errEn = {
  'invalid-path': 'Invalid project path',
  'not-found': 'The folder does not exist',
  'invalid-request': 'Invalid request',
  'invalid-content': 'content must be a string',
  'agents-read': 'Failed to read AGENTS.md',
  'agents-write': 'Failed to write AGENTS.md',
  'config-save': 'Failed to save config',
  'settings-write': 'Failed to update setting.json',
  'workspace-empty': 'Workspace not found or has no sessions',
  'order-write': 'Failed to persist ordering',
  'group-not-found': 'No group contains these sessions',
  'group-ambiguous': 'Cannot determine the group uniquely',
  'name-too-long': 'Alias too long (max 100 characters)',
  'name-invalid-chars': 'Alias must not contain newlines or control characters',
  'index-remap-failed': 'Failed to update the task index (config changes rolled back)',
  'index-error': 'Task index error',
  'index-busy': 'The task index is busy. Please retry shortly.',
  'vision-invalid': 'Invalid vision config',
  'vision-read': 'Failed to read zcode-vision.json',
  'vision-write': 'Failed to write zcode-vision.json',
  'vision-test': 'Vision test failed',
  'proxy-invalid': 'Proxy must look like http://127.0.0.1:7890, or be empty',
  'proxy-not-set': 'Set the proxy address first',
  'rtk-invalid': 'Invalid rtk config',
  'rtk-update': 'Failed to check rtk updates (GitHub Releases unreachable? Set a proxy in the Proxy tab)',
  'rtk-write': 'Failed to write the rtk config',
  'headroom-read': 'Failed to read headroom.json',
  'headroom-write': 'Failed to write headroom.json',
  'headroom-invalid': 'Invalid headroom setting',
  'headroom-plugin': 'headroom plugin not found (install it from the marketplace)',
  'headroom-sh': 'sh not found; cannot run the headroom plugin script',
  'headroom-action': 'The headroom action failed',
  'headroom-status': 'Failed to read the headroom status',
  'headroom-upgrade': 'headroom upgrade failed',
  'plugins-status': 'Failed to read the plugin list',
  'plugins-update': 'Failed to update plugins',
  'sync-invalid': 'Invalid sync settings',
  'sync-not-configured': 'Set the sync type to WebDAV and save the config first',
  'sync-remote-missing': 'No synced data on the server yet; upload from another computer first',
  'sync-remote-invalid': 'The URL already holds a different file; use another file path',
  'sync-request': 'The WebDAV request failed',
  'sync-run': 'Sync failed',
};

export function errText(res) {
  if (!res) return '';
  if (!isZhLocale()) {
    const en = res.code && errEn[res.code];
    if (en) return en;
  }
  return res.error || '';
}

export function h(tag, attrs, ...children) {
  const el = document.createElement(tag);
  if (attrs) {
    for (const [k, v] of Object.entries(attrs)) {
      if (k === 'class') el.className = v;
      else if (k === 'style') el.setAttribute('style', v);
      else if (k.startsWith('on') && typeof v === 'function') el.addEventListener(k.slice(2).toLowerCase(), v);
      else if (v === true) el.setAttribute(k, '');
      else if (v !== false && v !== undefined && v !== null) el.setAttribute(k, String(v));
    }
  }
  for (const c of children.flat(Infinity)) {
    if (c === undefined || c === null || c === false) continue;
    el.append(c.nodeType ? c : document.createTextNode(String(c)));
  }
  return el;
}

export function closeRadixMenu(contentEl) {
  try {
    contentEl.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', code: 'Escape', bubbles: true, cancelable: true }));
  } catch { /* ignore */ }
}

// 观察 Radix 弹层（下拉菜单/弹出框）出现，回调 content 元素
export function observeRadixPopups(onPopup) {
  const seen = new WeakSet();
  const check = (node) => {
    if (!(node instanceof HTMLElement)) return;
    if (node.hasAttribute('data-radix-popper-content-wrapper')) {
      // wrapper 先出现，content 在下一帧内插入
      requestAnimationFrame(() => {
        const content = node.firstElementChild;
        if (content && !seen.has(content)) {
          seen.add(content);
          onPopup(content);
        }
      });
    }
    // 兜底：直接观察 role=menu 的 content。延迟一帧再回调——Radix 偶尔分两帧渲染
    // （先挂 menu 容器、下一帧才填菜单项），立即回调时菜单项为空，调用方找不到
    // 锚点项就永远漏注入（菜单项填入不会再产生 role=menu 节点添加事件）
    if (node.getAttribute && node.getAttribute('role') === 'menu' && !seen.has(node)) {
      seen.add(node);
      requestAnimationFrame(() => {
        if (node.isConnected) onPopup(node);
      });
    }
  };
  const process = (mutations) => {
    for (const m of mutations) for (const n of m.addedNodes) check(n);
  };
  const observer = new MutationObserver(process);
  observer.observe(document.documentElement, { childList: true, subtree: true });
  return observer;
}

export function itemsOf(menuEl) {
  return [...menuEl.querySelectorAll('[role="menuitem"]')];
}

export function itemText(item) {
  return (item.textContent || '').trim();
}
